{
 "title": "Besu Node Monitor (Metrics + Logs)",
 "description": "Consolidated Besu Dashboard with Logs and TxPool",
 "tags": [
  "besu",
  "ethereum",
  "loki"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "system", "label": "System", "query": "ethereum_blockchain_height" }
  ]
 },
 "panels": [
  {
   "title": "Network Overview",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (ethereum_blockchain_height{instance=~\"$system\"})",
     "legendFormat": "Chain Height"
    },
    {
     "expr": "sum by (instance) (time() - besu_blockchain_chain_head_timestamp{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) (ethereum_peer_count{instance=~\"$system\"})",
     "legendFormat": "Peer Count"
    },
    {
     "expr": "sum by (instance) (ethereum_best_known_block_number{instance=~\"$system\"} - ethereum_blockchain_height{instance=~\"$system\"})"
    }
   ]
  },
  {
   "title": "Transaction Pool (Pending)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "besu_transaction_pool_transactions{instance=~\"$system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Time (Avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "1/rate(ethereum_blockchain_height{instance=~\"$system\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"$system\"}[1m])",
     "legendFormat": "CPU Time IRate [{{instance}}]"
    }
   ]
  },
  {
   "title": "Memory Used (Heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$system\", area=\"heap\"}",
     "legendFormat": "Heap {{instance}}"
    }
   ]
  },
  {
   "title": "Besu Error Logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{job=\"besu\", level=\"ERROR\"}"
    }
   ]
  }
 ]
}