{
 "title": "Besu Node Status",
 "tags": [
  "besu",
  "ethereum"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"besu\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Up Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current Block Height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ethereum_blockchain_height{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "besu_peers_connected_total{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Transaction Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "besu_transaction_pool_transactions{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Tx in Pool"
    }
   ]
  },
  {
   "title": "Block Import Time (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(besu_block_import_time_seconds_sum{job=\"$job\", instance=\"$instance\"}[5m]) / rate(besu_block_import_time_seconds_count{job=\"$job\", instance=\"$instance\"}[5m])",
     "legendFormat": "Avg Import Time"
    }
   ]
  }
 ]
}